### ISSUE TITLE
Incompatibility to Immersive Weathering

### ISSUE THREAD

**Issue by TheButterbrotMan** [0rc1nus/Overweight-Farming#26]
https://bytebin.lucko.me/rSYrGIzRPK

**Comment by mrsterner** [comment]
Update to 1.5.2

**Comment by TheButterbrotMan** [comment]
There is no 1.5.2 :(

![image](https://user-images.githubusercontent.com/64548098/178105032-b97c375c-e59a-473f-80ac-e7fcce9148a3.png)

**Comment by mrsterner** [comment]
![image](https://user-images.githubusercontent.com/32911664/178105104-9dee7276-1c7d-4dbf-9187-33e169f76b71.png)
