### ISSUE TITLE
Missing Inventory Textures/Models in 1.19-1.5.2-fabric

### ISSUE THREAD

**Issue by CosmicParticl** [0rc1nus/Overweight-Farming#27]
The issue only seems to impact the inventory views of the Cabbage Block, Onion Block, and Peeled Onion blocks
![2022-07-10_23 17 08](https://user-images.githubusercontent.com/54153712/178182348-96e17db5-f93c-4a00-8932-c132172ecb5c.png)
.

**Comment by SandWoodJones** [comment]
This is still happening with the bewitchment compatibility items ![image](https://user-images.githubusercontent.com/35671374/179885124-7fc307c1-5a0c-4d0d-92b8-66b21cd52e64.png)
